#ifndef __IhmFormationPrincFrameCatalogue__
#define __IhmFormationPrincFrameCatalogue__

/**
@file
Subclass of PrincFrameCatalogue, which is generated by wxFormBuilder.
*/

#include "Ihm.h"
#include "Main.h"
//// end generated include

/** Implementing PrincFrameCatalogue */
class IhmFormationPrincFrameCatalogue : public PrincFrameCatalogue
{
	protected:
		// Handlers for PrincFrameCatalogue events.
		void OnMenuAjouterFormationLGT( wxCommandEvent& event );
	public:
		/** Constructor */
		IhmFormationPrincFrameCatalogue( wxWindow* parent );
	//// end generated class members




};

#endif // __IhmFormationPrincFrameCatalogue__
