#ifndef __IhmFormationAjouterFormation__
#define __IhmFormationAjouterFormation__

/**
@file
Subclass of AjouterFormation, which is generated by wxFormBuilder.
*/

#include "Ihm.h"
#include "Main.h"
//// end generated include

/** Implementing AjouterFormation */
class IhmFormationAjouterFormation : public AjouterFormation
{
	protected:
		// Handlers for AjouterFormation events.
		void buttonConfirmerEvt( wxCommandEvent& event );
		void buttonAnnulerEvt( wxCommandEvent& event );
	public:
		/** Constructor */
		IhmFormationAjouterFormation( wxWindow* parent );
	//// end generated class members













};

#endif // __IhmFormationAjouterFormation__
